### ISSUE TITLE
Reference search with `:identifier` modifier not working

### ISSUE THREAD

**Issue by guillerglez88** [Aidbox/Issues#47]
Reference search with `:identifier` modifier not working at least in devbox:0.3.3-248-gbc91ced

request:

```GET /fhir/MedicationStatement?subject:identifier=http://domain.com/fhir/system-identifiers/customers|77```

response:

```total: 0```

query-sql:

```
SELECT "medicationstatement".*
FROM "medicationstatement"
WHERE ("medicationstatement".resource @> {
  "subject": {
    "id": "identifier/http://domain.com/fhir/system-identifiers/customers|77"
  }
}) LIMIT 100 OFFSET 0
```
as you can see, translation to pgsql query is wrong, since identifier is not been taken as modifier but as part of ref id
it isn't even separating system and value from identifier

**Comment by mlapshin** [comment]
fixed in `0.3.4-4-g4d482c5`

**Comment by guillerglez88** [comment]
`Reference:Identifier` still not fully behaving as token search.
Example:

Request:
```
0 | http://localhost:8888/fhir/Provenance
1 |   ?_count=1
2 |   &_sort=-when
3 |   &target:identifier=http://onelogic.com/fhir/onerx-identifiers/supplements|
4 |   &agent:identifier=http://onelogic.com/fhir/ehr-services|ehr-svc-pharmacy
5 |   &agent:identifier=http://onelogic.com/fhir/data-sources|onerx&_format=json
```

Response sql:
```
0 | "query-sql": [
1 |     "SELECT "provenance".* FROM "provenance" WHERE (("provenance".resource @> ?) AND ("provenance".resource @> ?) AND ("provenance".resource @> ?) AND ("provenance".resource @> ?)) ORDER BY knife_extract_max_timestamptz("provenance".resource, ?) DESC LIMIT ? OFFSET ?",
2 |     "{"target":[{"identifier":{"value":"http://onelogic.com/fhir/onerx-identifiers/supplements|"}}]}",
3 |     "{"agent":[{"who":{"identifier":{"system":"http://onelogic.com/fhir/ehr-services","value":"ehr-svc-pharmacy"}}}]}",
4 |     "{"agent":[{"who":{"identifier":{"system":"http://onelogic.com/fhir/data-sources","value":"onerx"}}}]}",
5 |     "{"target":[{"id":"1"}]}",
6 |     "[]",
7 |     1,
8 |     0
9 | ]
```

Notice:

request's line 3 is translated to response's line 2, where `value` is set instead of `system`

**Comment by niquola** [comment]
Please test in 0.4.1-SNAPSHOT
